name: dapter
description: A uniform interface for the database drivers
version: 0.0.1
author: Anton Astashov <anton.astashov@gmail.com>
homepage: https://github.com/astashov/dapter

environment:
  sdk: '>=1.0.0 <2.0.0'
